homepage:
    path: /{_locale}
    #controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    controller: App\Controller\HubsHost\HomepageController::index
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: base.html.twig
        _locale: '%locale%'

controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
